baseURL = 'https://przemekhys.dev/'
languageCode = 'pl-pl'
title = 'Notatki Przemka'
theme = 'PaperMod'

[params]
  description = "Moje autorskie notatki o tech i ogrodnictwie"
  author = "Przemek"
  
[menu]
  [[menu.main]]
    name = "Posty"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "O mnie"
    url = "/about/"
    weight = 2